sudo: false

language: go

go:
  - 1.5
  - 1.6
  - 1.11
  - 1.12
  - 1.13
  - 1.14
  - 1.15
  - 1.16
  - 1.17
  - tip

install:
  - go get -d -t ./...

script:
  - go test -v ./...

matrix:
  allow_failures:
    - go: tip

  fast_finish: true
